import { Route } from "./types.ts";

export const demo: Route[][] = [
  [
    {
      grade: "7a+",
      color: "bleu",
      author: "Seb",
      setAtYear: "2021",
      setAtMonth: "Oct",
    },
    {
      grade: "5b",
      color: "rouge",
      author: undefined,
      setAtYear: "2022",
      setAtMonth: "Oct",
    },
    {
      grade: "4b",
      color: "beige",
      author: undefined,
      setAtYear: "2023",
      setAtMonth: "Fev",
    },
  ],
  [
    {
      grade: "5b",
      color: "violet",
      author: undefined,
      setAtYear: "2022",
      setAtMonth: "Oct",
    },
    {
      grade: "5a+",
      color: "rose",
      author: undefined,
      setAtYear: "2022",
      setAtMonth: "Oct",
    },
    {
      grade: "5c+",
      color: "vert",
      author: undefined,
      setAtYear: "2022",
      setAtMonth: "Oct",
    },
    {
      grade: "5c+",
      color: "jaune",
      author: undefined,
      setAtYear: "2022",
      setAtMonth: "Oct",
    },
  ],
  [
    {
      grade: "6c",
      color: "noir",
      author: undefined,
      setAtYear: "2021",
      setAtMonth: "Oct",
    },
    {
      grade: "5b",
      color: "orange",
      author: undefined,
      setAtYear: "2022",
      setAtMonth: "Oct",
    },
    {
      grade: "6a+",
      color: "bleu",
      author: undefined,
      setAtYear: "2023",
      setAtMonth: "Fev",
    },
    {
      grade: "5c+",
      color: "blanc",
      author: undefined,
      setAtYear: "2023",
      setAtMonth: "Fev",
    },
  ],
  [
    {
      grade: "5b",
      color: "rose",
      author: undefined,
      setAtYear: "2021",
      setAtMonth: "Oct",
    },
    {
      grade: "6b",
      color: "jaune",
      author: undefined,
      setAtYear: "2023",
      setAtMonth: "Fev",
    },
    {
      grade: "6a",
      color: "beige",
      author: undefined,
      setAtYear: "2021",
      setAtMonth: "Oct",
    },
  ],
  [
    {
      grade: "5b",
      color: "noir",
      author: undefined,
      setAtYear: "2022",
      setAtMonth: "Oct",
    },
    {
      grade: "7a",
      color: "orange",
      author: undefined,
      setAtYear: "2022",
      setAtMonth: "Oct",
    },
    {
      grade: "4c",
      color: "blanc",
      author: undefined,
      setAtYear: "2021",
      setAtMonth: "Oct",
    },
  ],
  [
    {
      grade: "5a",
      color: "vert",
      author: undefined,
      setAtYear: "2021",
      setAtMonth: "Oct",
    },
    {
      grade: "5c",
      color: "bleu",
      author: undefined,
      setAtYear: "2022",
      setAtMonth: "Oct",
    },
    {
      grade: "6b+",
      color: "violet",
      author: undefined,
      setAtYear: "2022",
      setAtMonth: "Oct",
    },
  ],
  [
    {
      grade: "6a",
      color: "gris",
      author: undefined,
      setAtYear: "?",
      setAtMonth: "?",
    },
    {
      grade: "5b+",
      color: "rose",
      author: undefined,
      setAtYear: "2022",
      setAtMonth: "Oct",
    },
    {
      grade: "6a+",
      color: "jaune",
      author: undefined,
      setAtYear: "2021",
      setAtMonth: "Oct",
    },
    {
      grade: "6b+",
      color: "orange",
      author: undefined,
      setAtYear: "2021",
      setAtMonth: "Oct",
    },
  ],
  [
    {
      grade: "6a+",
      color: "bleu",
      author: undefined,
      setAtYear: "2022",
      setAtMonth: "Oct",
    },
    {
      grade: "6a",
      color: "violet",
      author: undefined,
      setAtYear: "2023",
      setAtMonth: "Fev",
    },
    {
      grade: "6b",
      color: "rouge",
      author: undefined,
      setAtYear: "2023",
      setAtMonth: "Fev",
    },
  ],
  [
    {
      grade: "5b+",
      color: "noir",
      author: undefined,
      setAtYear: "2023",
      setAtMonth: "Fev",
    },
    {
      grade: "6b",
      color: "orange",
      author: undefined,
      setAtYear: "2022",
      setAtMonth: "Fev",
    },
    {
      grade: "6b+",
      color: "vert",
      author: undefined,
      setAtYear: "2022",
      setAtMonth: "Oct",
    },
    {
      grade: "6b",
      color: "rose",
      author: undefined,
      setAtYear: "2023",
      setAtMonth: "Fev",
    },
  ],
  [
    {
      grade: "6b+",
      color: "jaune",
      author: undefined,
      setAtYear: "2023",
      setAtMonth: "Fev",
    },
    {
      grade: "5c+",
      color: "bleu",
      author: undefined,
      setAtYear: "2022",
      setAtMonth: "Oct",
    },
    {
      grade: "7a",
      color: "beige",
      author: undefined,
      setAtYear: "2023",
      setAtMonth: "Fev",
    },
  ],
  [
    {
      grade: "6c",
      color: "blanc",
      author: undefined,
      setAtYear: "2022",
      setAtMonth: "Avr",
    },
    {
      grade: "6c",
      color: "orange",
      author: undefined,
      setAtYear: "2022",
      setAtMonth: "Avr",
    },
    {
      grade: "5c",
      color: "vert",
      author: undefined,
      setAtYear: "2022",
      setAtMonth: "Avr",
    },
  ],
  [
    {
      grade: "6a+",
      color: "rose",
      author: undefined,
      setAtYear: "2022",
      setAtMonth: "Avr",
    },
    {
      grade: "6b+",
      color: "bleu",
      author: "Baptiste",
      setAtYear: "2022",
      setAtMonth: "Avr",
    },
    {
      grade: "6a",
      color: "jaune",
      author: undefined,
      setAtYear: "2022",
      setAtMonth: "Avr",
    },
  ],
  [
    {
      grade: "5a+",
      color: "orange",
      author: undefined,
      setAtYear: "2019",
      setAtMonth: "Fev",
    },
    {
      grade: "6c",
      color: "rouge",
      author: "Baptiste",
      setAtYear: "2022",
      setAtMonth: "Oct",
    },
    {
      grade: "6b",
      color: "violet",
      author: undefined,
      setAtYear: "2023",
      setAtMonth: "Fev",
    },
  ],
  [
    {
      grade: "6a+",
      color: "bleu",
      author: undefined,
      setAtYear: "2022",
      setAtMonth: "Fev",
    },
    {
      grade: "6a+",
      color: "jaune",
      author: undefined,
      setAtYear: "2022",
      setAtMonth: "Avr",
    },
    {
      grade: "7a+",
      color: "vert",
      author: "Ivanne",
      setAtYear: "2023",
      setAtMonth: "Fev",
    },
  ],
  [
    {
      grade: "5b+",
      color: "rose",
      author: undefined,
      setAtYear: "?",
      setAtMonth: "?",
    },
    {
      grade: "6b",
      color: "blanc",
      author: undefined,
      setAtYear: "2019",
      setAtMonth: "Fev",
    },
    {
      grade: "6a+",
      color: "rouge",
      author: undefined,
      setAtYear: "?",
      setAtMonth: "?",
    },
  ],
  [
    {
      grade: "6b",
      color: "bleu",
      author: undefined,
      setAtYear: "?",
      setAtMonth: "?",
    },
    {
      grade: "5c+",
      color: "vert",
      author: undefined,
      setAtYear: "?",
      setAtMonth: "?",
    },
    {
      grade: "7a",
      color: "orange",
      author: "Baptiste",
      setAtYear: "2022",
      setAtMonth: "Fev",
    },
    {
      grade: "6a+",
      color: "noir",
      author: "Baptiste",
      setAtYear: "2022",
      setAtMonth: "Fev",
    },
  ],
];
