// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[club]/edit.tsx";
import * as $1 from "./routes/[club]/pdf.tsx";
import * as $2 from "./routes/[club]/view.tsx";
import * as $3 from "./routes/_404.tsx";
import * as $4 from "./routes/_app.tsx";
import * as $5 from "./routes/api/sync.ts";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/pdf-test.tsx";
import * as $$0 from "./islands/Editor.tsx";

const manifest = {
  routes: {
    "./routes/[club]/edit.tsx": $0,
    "./routes/[club]/pdf.tsx": $1,
    "./routes/[club]/view.tsx": $2,
    "./routes/_404.tsx": $3,
    "./routes/_app.tsx": $4,
    "./routes/api/sync.ts": $5,
    "./routes/index.tsx": $6,
    "./routes/pdf-test.tsx": $7,
  },
  islands: {
    "./islands/Editor.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
